# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Githook < Formula
  desc "Webhook router + worker SDK for GitHub, GitLab, Bitbucket. Route events by rules and consume via Watermill."
  homepage "https://github.com/relaymesh/githook"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/relaymesh/githook/releases/download/v0.0.6/githook_0.0.6_darwin_amd64.tar.gz"
      sha256 "d3bcecee92db3facb50b28ea90b328f7d245a7e448eb54f03b992a08106102b3"

      define_method(:install) do
        bin.install "githook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/relaymesh/githook/releases/download/v0.0.6/githook_0.0.6_darwin_arm64.tar.gz"
      sha256 "a083dfef543cad11a03e5bd9d99849d81c7f7551a7b3a650442e30cf7596cc0d"

      define_method(:install) do
        bin.install "githook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/relaymesh/githook/releases/download/v0.0.6/githook_0.0.6_linux_amd64.tar.gz"
      sha256 "cd18cee41b3fc76f714e9e7cae190a221ec51fc1b06fbe4caf49f2823b757919"
      define_method(:install) do
        bin.install "githook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/relaymesh/githook/releases/download/v0.0.6/githook_0.0.6_linux_arm64.tar.gz"
      sha256 "d323d79d21ce47248d210634836fc1a648c0c9e1c51d4611a63ee8f3aa4c74b1"
      define_method(:install) do
        bin.install "githook"
      end
    end
  end

  test do
    system "#{bin}/githook", "--help"
  end
end
