# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Githook < Formula
  desc "Webhook router + worker SDK for GitHub, GitLab, Bitbucket. Route events by rules and consume via Watermill."
  homepage "https://github.com/relaymesh/githook"
  version "0.0.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/relaymesh/githook/releases/download/v0.0.13/githook_0.0.13_darwin_amd64.tar.gz"
      sha256 "15c8cad51cbc1feadd88c31f0431f89c5860e1e10afab31d025324d29b3620e3"

      define_method(:install) do
        bin.install "githook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/relaymesh/githook/releases/download/v0.0.13/githook_0.0.13_darwin_arm64.tar.gz"
      sha256 "f52ad0e97affa5cab426f653be91af7ee2160dbd12256b6fbd987e311662879e"

      define_method(:install) do
        bin.install "githook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/relaymesh/githook/releases/download/v0.0.13/githook_0.0.13_linux_amd64.tar.gz"
      sha256 "090f008cdac2839b4c8a25596f908e2263352a95d33b6474fd19a3ce8b3dc453"
      define_method(:install) do
        bin.install "githook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/relaymesh/githook/releases/download/v0.0.13/githook_0.0.13_linux_arm64.tar.gz"
      sha256 "8e87825a507c5fed3fe15afccab2d362f7527ef3fe34e2ea4a191b82977dd17a"
      define_method(:install) do
        bin.install "githook"
      end
    end
  end

  test do
    system "#{bin}/githook", "--help"
  end
end
