# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Githook < Formula
  desc "Webhook router + worker SDK for GitHub, GitLab, Bitbucket. Route events by rules and consume via Watermill."
  homepage "https://github.com/relaymesh/githook"
  version "0.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/relaymesh/githook/releases/download/v0.0.11/githook_0.0.11_darwin_amd64.tar.gz"
      sha256 "50f53c9e214b01e4c295a5a1805908f8bee53c61ac760e252975c1e9e8a0105d"

      define_method(:install) do
        bin.install "githook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/relaymesh/githook/releases/download/v0.0.11/githook_0.0.11_darwin_arm64.tar.gz"
      sha256 "d3d0534b315a87bad4ab18321788ba2bc88d645cf02ae9b84755b82724882982"

      define_method(:install) do
        bin.install "githook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/relaymesh/githook/releases/download/v0.0.11/githook_0.0.11_linux_amd64.tar.gz"
      sha256 "647eca58722ba5570ec69f923842cd7e6e9b498f0d8a54dede250192dad5f8e4"
      define_method(:install) do
        bin.install "githook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/relaymesh/githook/releases/download/v0.0.11/githook_0.0.11_linux_arm64.tar.gz"
      sha256 "f0ee0c3f9651ca92726d0e3168d042e91a73a5d62d6b9dd1f8c42d095c5707d8"
      define_method(:install) do
        bin.install "githook"
      end
    end
  end

  test do
    system "#{bin}/githook", "--help"
  end
end
