# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Relaymesh < Formula
  desc "Webhook router + worker SDK for GitHub, GitLab, Bitbucket. Route events by rules and consume via Watermill."
  homepage "https://github.com/relaymesh/relaymesh"
  version "0.0.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/relaymesh/relaymesh/releases/download/v0.0.21/relaymesh_0.0.21_darwin_amd64.tar.gz"
      sha256 "9a8d935afd837a25b6e6525233e7dfae734059dd938692d323f660642b940af1"

      define_method(:install) do
        bin.install "relaymesh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/relaymesh/relaymesh/releases/download/v0.0.21/relaymesh_0.0.21_darwin_arm64.tar.gz"
      sha256 "97c3ff60a4233382ea6a9c00b7d0b9894463c11be4e42b476b395c643d6c197e"

      define_method(:install) do
        bin.install "relaymesh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/relaymesh/relaymesh/releases/download/v0.0.21/relaymesh_0.0.21_linux_amd64.tar.gz"
      sha256 "92855a787e57f140608836dab621557805031615925a8bca6fb105333a6b5d08"
      define_method(:install) do
        bin.install "relaymesh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/relaymesh/relaymesh/releases/download/v0.0.21/relaymesh_0.0.21_linux_arm64.tar.gz"
      sha256 "afae44550989e59cbc47f4a47167ba2de3fe366950e6bf99f2d79ad42552b587"
      define_method(:install) do
        bin.install "relaymesh"
      end
    end
  end

  test do
    system "#{bin}/relaymesh", "--help"
  end
end
