# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Relaymesh < Formula
  desc "Webhook router + worker SDK for GitHub, GitLab, Bitbucket. Route events by rules and consume via Watermill."
  homepage "https://github.com/relaymesh/relaymesh"
  version "0.0.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/relaymesh/relaymesh/releases/download/v0.0.19/relaymesh_0.0.19_darwin_amd64.tar.gz"
      sha256 "51e345c045a0f82fb01e564beebdabd8839f50c2bc067b1a345a1f952a0ce958"

      define_method(:install) do
        bin.install "relaymesh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/relaymesh/relaymesh/releases/download/v0.0.19/relaymesh_0.0.19_darwin_arm64.tar.gz"
      sha256 "e243414091ab17c862ef2a07ad49b19c8e4e563378d2fa103a129901368b24d8"

      define_method(:install) do
        bin.install "relaymesh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/relaymesh/relaymesh/releases/download/v0.0.19/relaymesh_0.0.19_linux_amd64.tar.gz"
      sha256 "81e55e60ccb78f4571177322e7e30ac08801203bf6a3bf7342952019bb2b5439"
      define_method(:install) do
        bin.install "relaymesh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/relaymesh/relaymesh/releases/download/v0.0.19/relaymesh_0.0.19_linux_arm64.tar.gz"
      sha256 "5e323bf093a7fd5daccf8a078b2fef088bb1817ced297b731fb1acf6a2e273cd"
      define_method(:install) do
        bin.install "relaymesh"
      end
    end
  end

  test do
    system "#{bin}/relaymesh", "--help"
  end
end
